<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Promise Error Handling</title>
		<link rel="stylesheet" href="../../base.css" />
	</head>
	<body>
		<h2>Error handling promises</h2>
		<ul>
			<li>
				You Can put one .catch at the end of a promise chain for error
				handling (one .catch to many then statements)
			</li>
			<li>
				the promise chain will stop at the point in the chain the error
				in triggered
			</li>
			<li>leaving the rest unresolved.</li>
		</ul>

		<script>
			function makePizza(toppings = []) {
				return new Promise(function (resolve, reject) {
					if (toppings.includes('pineapple')) {
						reject("I guess we don't like 🍍 on our 🍕.")
					}

					const bakeTime = 500 + toppings.length * 200

					setTimeout(function () {
						resolve(
							`Here is your ${
								toppings ? toppings.join(', ') : 'Plain'
							} pizza! 🍕`
						)
					}, bakeTime)
					// resolve(`Here is your ${toppings.join(' ')} pizza. 🍕`)
					// NOTE: if not reject promise
					// reject(
					//     new Error("No pizza's around")
					// )
				})
				return pizzaPromise
			}

			makePizza(['cheese', 'pineapple'])
				.then((pizza) => console.log(pizza))
				//NOTE: without a catch "Uncaught (in promise) TypeError: I guess we don't like 🍍 on our 🍕."
				.catch((error) => {
					console.log(error)
				})

			const p1 = makePizza(['pep'])
			const p2 = makePizza(['cheese'])
			const p3 = makePizza(['pineapple'])

            // .all vs .allSettled
            //NOTE: all will fail it all promises are not resolved, where .allSettled will return an array of results either way. 
			const myPizza = Promise.allSettled([p1, p2, p3])

			myPizza
				.then((pizza) => {
					console.log(pizza)
				})
				.catch((err) => console.log(err))
		</script>
	</body>
</html>
